; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon May 24 2021 07:21:15 GMT-0400 (Eastern Daylight Time)
G1 R1 X0 Y0 Z20 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
M83                  ; relative extruder moves
;G1 E10 F3600         ; extrude 10mm of filament

