; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon May 24 2021 07:21:16 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

